### ISSUE TITLE
ZigBrains breaks Rust plugin in CLion

### ISSUE THREAD

**Issue by emtek995** [FalsePattern/ZigBrains#10]
When I load a rust project with the ZigBrains plugin loaded it breaks the rust lsp. I no longer get completions for rust and hover actions no longer work. If I unload the ZigBrains plugin and restart the rust plugin works as expected.

**Comment by asorgejr** [comment]
It seems to break LSPs for many languages in my project. I have personally observed .js, .ts and .rs analysis are all affected by this plugin.

**Comment by FalsePattern** [comment]
Does this still happen?

**Comment by FalsePattern** [comment]
No longer relevant since 16.0.0-pre1, LSP integration is handled by LSP4IJ.
