### ISSUE TITLE
zigbrains autocomplete arguments are generated as text rather than placeholders

### ISSUE THREAD

**Issue by chrispickard** [FalsePattern/ZigBrains#20]
thanks so much for this plugin, I can finally use clion for zig which is something I've wanted for a long time. however, when zigbrains generates autocomplete arguments they are regular text, rather than the typical argument placeholders. I made a screen cap to show the situation

https://github.com/FalsePattern/ZigBrains/assets/1438690/71b63d1e-3a0c-4172-b3e8-7715e1c77198

 
CLion 2023.2.2
Build #CL-232.9921.42, built on September 12, 2023
Licensed to Chris Pickard
Subscription is active until March 2, 2024.
Runtime version: 17.0.7+7-nixos amd64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o.
Linux 6.2.0-76060200-generic
GC: G1 Young Generation, G1 Old Generation
Memory: 4096M
Cores: 16
Registry:
    suggest.all.run.configurations.from.context=true
    debugger.new.tool.window.layout=true
    run.processes.with.pty=TRUE
    ide.experimental.ui=true
    debugger.attach.dialog.enabled=true

Non-Bundled Plugins:
    org.rust.lang (0.4.201.5424-232)
    IdeaVIM (2.6.0-eap.2)
    com.arcticicestudio.nord.jetbrains (0.13.0)
    nl.rubensten.texifyidea (0.9.1)
    com.falsepattern.zigbrains (0.8.0)
    ru.adelf.idea.dotenv (2023.2)
    mobi.hsz.idea.gitignore (4.5.1)
    nix-idea (0.4.0.10)

Current Desktop: Undefined

**Comment by FalsePattern** [comment]
This should be fixed now.

**Comment by FalsePattern** [comment]
No longer relevant since 16.0.0-pre1, autocomplete is handled by LSP4IJ.
