### ISSUE TITLE
feature request: it would be great to be able to go to definition in the stdlib

### ISSUE THREAD

**Issue by chrispickard** [FalsePattern/ZigBrains#21]
I'm new to zig and one way I've been learning is by jumping directly from a stdlib function into that function's definition and reading what it does and what other functions and structs exist in that file. this works in emacs with eglot but I can't get it to work with zigbrains.

thanks for this great plugin!

**Comment by JensvandeWiel** [comment]
Hey! can you try the fix in #13

**Comment by FalsePattern** [comment]
Fixed in 12.0.0
