### ISSUE TITLE
Build summary is colorless

### ISSUE THREAD

**Issue by ZlatyChlapec** [FalsePattern/ZigBrains#26]
Running `build` command with option `--summary all` produces colorless output.

<img width="637" alt="image" src="https://github.com/FalsePattern/ZigBrains/assets/6187861/5c77adc6-dc74-443c-bc23-12970a2e4fe8">

Expected output:
<img width="471" alt="image" src="https://github.com/FalsePattern/ZigBrains/assets/6187861/24205e5a-88ba-442c-b262-1aaae9edecba">

**Comment by FalsePattern** [comment]
Fixed in 13.0.0
