### ISSUE TITLE
formatting on 0.10.0 does no indenting

### ISSUE THREAD

**Issue by Khitiara** [FalsePattern/ZigBrains#31]
![image](https://github.com/FalsePattern/ZigBrains/assets/3117019/9313cfcd-4b09-467e-af52-0e6ec02ca28c)

happens with default format settings after updating zigbrains

**Comment by JensvandeWiel** [comment]
Tested, can confirm when you run formatting it removes indentation.

**Comment by JensvandeWiel** [comment]
While on the formatter, we need to switch to the lsp, only i have no where near of an idea on how to do it. I dont have much experience in jetbrains plugins. @FalsePattern can you help on this part or guide me on how to implement the formatting trough the lsp?

**Comment by Khitiara** [comment]
gonna add that i was using clion nova, in case its a weird thing specific to some jetbrains tools

**Comment by JensvandeWiel** [comment]
But why did the indenting not work when typing or making a new block

**Comment by FalsePattern** [comment]
Fixed in 11.0.0
