### ISSUE TITLE
Numbers complete to number types

### ISSUE THREAD

**Issue by itsmagu** [FalsePattern/ZigBrains#32]
![image](https://github.com/FalsePattern/ZigBrains/assets/95685391/2cda78d4-f3bc-4525-b78e-d9d22f0aabf5)
When I type 3, I get the option to make a f32!
I just want a literal not the type!

**Comment by FalsePattern** [comment]
You can press escape to hide the autocomplete popup. This is standard intellij IDE behaviour.

**Comment by FalsePattern** [comment]
Does this still happen on 16.0.0-pre1?
