### ISSUE TITLE
Find Usages not working

### ISSUE THREAD

**Issue by abovestratosphere** [FalsePattern/ZigBrains#39]
Thanks for the plugin, it's working great in almost every aspect. One thing I couldn't get to work is "Find Usages" which is a very common workflow. My hotkey for this does nothing. My expected workflow is to hover over a variable, function, or whatever and hit the usage hotkey and have a popup window with all the usages of that across the project. Is this supported by this plugin? The README for this project does mention "find usages" as a feature so am I doing something wrong?

I'm using zigbrains 13.1.0-241 in CLion.

**Comment by FalsePattern** [comment]
Should be fixed in 13.1.1
