### ISSUE TITLE
Debugging once using Zig Build with dependencies defined in build.zig.zon

### ISSUE THREAD

**Issue by timsavage** [FalsePattern/ZigBrains#41]
This may be a limitation of the zig tooling rather than this plugin.

Using a Zig-Run does not use the `build.zig` and `build.zig.zon` dependencies causing builds to fail where dependencies are required. 

Using a Zig-Build will successfully build, and adding the run argument will allow a build to subsequently be run. However, the debugger gets stuck at `Connecting`. Have tested with both GDB and LLDB.

Plugin version: 13.1.1-233
CLion version: 2023.3.4
Zig: 0.12....nightly
ZLS: 0.12...nightly
OS: Ubuntu 22.04

**Comment by timsavage** [comment]
After investigating more, I've found this is more of an issue with the Zig toolchain.

For anybody else encountering this problem, here is how to work around the issue and get things working.

1. Once you start using `zig build` with dependencies - `ZigTest` and `ZigRun` will no longer work (will cause build failures)
2. Replace all of your run configs with the build versions:
   * Create a ZigBuild configuration with the _Extra command line arguments_ `test` for tests
3. For Debugging add a `Native Application` run config
   * You may need add a target 
   * Select the executable generated by you build in `./zig-out/bin`
   * In the _Before Launch_ section replace any actions with your `ZigBuild Build` run-config so any re-compilation is done on run.

**Comment by FalsePattern** [comment]
The plugin already supports this, in the ZigBuild task type, you need to directly specify the executable generated by your zig build inside the task itself, this is effectively what you're doing with the Native Application solution, but integrated with the toolchain system.
![image](https://github.com/FalsePattern/ZigBrains/assets/30945458/f4cc8f15-1a8e-49cb-ba4e-4ae47832f711)

**Comment by FalsePattern** [comment]
Yep, i will add that in the next update

**Comment by FalsePattern** [comment]
Fixed in 13.2.0, debugging `Zig build` type intellij tasks should now work, even if you set the build step to `run`.

**Comment by timsavage** [comment]
Thanks very much, that works good.

Cheers
