### ISSUE TITLE
A confusing error message when zig is configured without ZLS

### ISSUE THREAD

**Issue by obask** [FalsePattern/ZigBrains#43]
It took me a while to decipher what this means:
![Screenshot 2024-04-14 at 12 33 09 PM](https://github.com/FalsePattern/ZigBrains/assets/13053173/a95642cc-ea1d-4c2a-90ac-a36e0aa67204)

### I would suggest one of possible resolutions:
1. Merge zig and ZLS settings pages together to avoid confusion
2. Or make messaging more clear: add a note to zig settings that it doesn't setup ZLS and change the error message to point users to a specific settings page and a field where they provide a path to their zls binary.

**Comment by FalsePattern** [comment]
Fixed in 14.0.0, I've unified the two configs and also added special detection for when ZLS is completely missing instead of just treating it as an incorrect path.
