### ISSUE TITLE
Debugging a trivial void main function under Windows breaks the variable inspector

### ISSUE THREAD

**Issue by Macfly** [FalsePattern/ZigBrains#46]
followed all the instructions but when debugging the variables are not shown as seen below:
![image](https://github.com/FalsePattern/ZigBrains/assets/1222059/d071d431-8794-4e72-9659-d7a707f89ac5)

how can I find what's wrong?

**Comment by FalsePattern** [comment]
Can confirm, this also happens on my system.

Oddly enough, changing the return type of the function from `void` to `!void` seems to fix this, but I have no idea why.

It might just be an odd interaction between the microsoft debugger and code generated by the zig compiler.

I'll look into this.

**Comment by FalsePattern** [comment]
Fixed in commit 5b8613fcd0e93209a1b574e8ccc73d475d1fc607, an update will be released shortly.

**Comment by FalsePattern** [comment]
Fixed in 14.2.0
