### ISSUE TITLE
Code completion includes redundant characters at the beginning of the first line

### ISSUE THREAD

**Issue by whisper-bye** [FalsePattern/ZigBrains#49]
version: 14.3.0-241

In an empty file,

![image](https://github.com/FalsePattern/ZigBrains/assets/3895096/14b4011d-2b78-4d79-adf5-c7af12f8ffd4)

![1716201562131](https://github.com/FalsePattern/ZigBrains/assets/3895096/5aaf24c2-74a9-454e-9990-94c2cf8f5e5f)

But if the cursor is on the second line, there is no problem.

**Comment by FalsePattern** [comment]
Fixed in 14.4.0
