### ISSUE TITLE
No output in the Run window

### ISSUE THREAD

**Issue by CJFEdu** [FalsePattern/ZigBrains#51]
I'm not getting any output when I use the run buttons in Intellij.  All I'm running is the default hello world and all I get is the run command and an exit with code 0.  I tried running the example fail test code and got an exit code1, but no other result.

When I go to run window and type in `zig run main.zig` it works fine though.

Any help is appreciated.

**Comment by FalsePattern** [comment]
Does this also happen on 15.0.3 or only on 15.1.0?

**Comment by CJFEdu** [comment]
I've only been able to test it on 15.1.0.  I tried downloading and installing 15.0.3 from disk and Intellij just froze up.  The project structure never loaded after the restart.  I tried going to the settings to see if it needed to be pointed to the Zig files, and the Languages and Frameworks page for Zig just showed a loading icon.

**Comment by FalsePattern** [comment]
Should be fixed in 15.1.1

**Comment by CJFEdu** [comment]
Confirmed it working.  Thanks again.
