### ISSUE TITLE
Support "Semantic highlighting"

### ISSUE THREAD

**Issue by OndraVoves** [FalsePattern/ZigBrains#52]
This is one feature that i miss and really need it =D (probably is not hard to implement)

PS.: Nice work ;)

**Comment by FalsePattern** [comment]
> This is one feature that i miss and really need it =D (probably is not hard to implement)
> 
> PS.: Nice work ;)

Semantic highlighting is already supported through ZLS. See: https://github.com/FalsePattern/ZigBrains?tab=readme-ov-file#quick-setup-guide-for-zig-and-zls

**Comment by OndraVoves** [comment]
Sry bad description. I mean this  "Semantic highlighting"  https://blog.jetbrains.com/pycharm/2017/01/make-sense-of-your-variables-at-a-glance-with-semantic-highlighting/

**Comment by FalsePattern** [comment]
ZigBrains has no concept of local variables as all semantic information is provided by ZLS, so please send this feature request to them.

Implementing this inside ZigBrains would require a complete rewrite of the plugin.
