### ISSUE TITLE
What about using LSP4IJ ?

### ISSUE THREAD

**Issue by angelozerr** [FalsePattern/ZigBrains#53]
I noticed that you have implemented your own lsp support, but I would like to notify you that it exists now a free LSP support for IntelliJ https://github.com/redhat-developer/lsp4ij

 * You can see the current LSP support at https://github.com/redhat-developer/lsp4ij/blob/main/docs%2FLSPSupport.md

 * LSP4IJ provides an LSP console to show LSP traces and see the state of language server https://github.com/redhat-developer/lsp4ij/blob/main/docs%2FUserGuide.md

 * If you want to play with LSP4IJ and your language server without developping an IJ plugin please read https://github.com/redhat-developer/lsp4ij/blob/main/docs%2FUserDefinedLanguageServer.md

 * If you want to integrate your ls in an IJ plugin please read https://github.com/redhat-developer/lsp4ij/blob/main/docs%2FDeveloperGuide.md

**Comment by FalsePattern** [comment]
My current LSP integration is based on a personalized/ZLS-specialized derivative of [LSP4IntelliJ](https://github.com/ballerina-platform/lsp4intellij).

Unfortunately, it doesn't seem like LSP4IJ support core functionality that ZigBrains depends on, such as `textDocument/semanticTokens` (for *really good* code coloring), so migrating over would be a downgrade compared to the fork of lsp4intellij integrated into ZigBrains.

**Comment by angelozerr** [comment]
Thanks @FalsePattern for your answer and I understand that you can use LSP4IJ for now.

The issue exists https://github.com/redhat-developer/lsp4ij/issues/238

It is amazing that you have implemented this semanticTokens. I will see your code  to try to implement the feature.

Is there any other support which misses in LSP4IJ ?

/cc @fbricon

**Comment by FalsePattern** [comment]
The way I use semanticTokens is the following:
1. A re-highlighting request caused by various events calls into the semantic highlighting wrapper method
2. The semanic token data is fetched (either full, or deltas)
3. For each semantic token edit, it's decoded using `TokenDecoder`, which uses the color values from ZigAttributes, which are exposed in the language color settings gui. This is a hardcoded set of semantic tokens, so any change in ZLS's tokens needs a ZigBrains update to compensate.
4. Lastly, i just use these range tokens to add/remove highlighter blocks via `Editor.getMarkupModel() .getAllHighlighters,removeAllHighlighters,removeHighlighter,addRangeHighlighter`
Relevant code:
[ZLSEditorEventManager.java](https://github.com/FalsePattern/ZigBrains/blob/c1f1dd88f14e0c3b631042d92d3880e55670c34c/modules/zig/src/main/java/com/falsepattern/zigbrains/zig/lsp/ZLSEditorEventManager.java#L62)
[HighlightingUtil.java](https://github.com/FalsePattern/ZigBrains/blob/c1f1dd88f14e0c3b631042d92d3880e55670c34c/modules/zig/src/main/java/com/falsepattern/zigbrains/zig/util/HighlightingUtil.java#L37)
[SemaEdit, SemaRange, ZigAttributes](https://github.com/FalsePattern/ZigBrains/tree/master/modules/zig/src/main/java/com/falsepattern/zigbrains/zig/ide)

**Comment by angelozerr** [comment]
Thanks for your feedback.

I wonder if it dhould be cleaner to provide  an implementation of semantic highlighting like explained at https://plugins.jetbrains.com/docs/intellij/syntax-highlighting-and-error-highlighting.html ?

**Comment by FalsePattern** [comment]
In the initial versions of ZigBrains, I was completely avoiding the PSI system because it felt overwhelming to try to glue it together with LSP4IntelliJ, which used it's own purely text-based system, so I had to rely on non-PSI apis for the semantic token highlighting, and I just never got around to porting it over to the correct PSI-based highlighter.

**Comment by angelozerr** [comment]
> In the initial versions of ZigBrains, I was completely avoiding the PSI system because it felt overwhelming to try to glue it together with LSP4IntelliJ, which used its own purely text-based system, so I had to rely on non-PSI apis for the semantic token highlighting, and I just never got around to porting it over to the correct PSI-based highlighter once I eventually gave in and implemented a proper PSI parser for zig.
> 
> (This is also the biggest reason why i would gladly migrate to LSP4IJ, the ballerina lsp adapter is just a maintenance nightmare at this point.)

I see totally what you mean and it was very hard to implement lsp feature without having a PsiFile parsed with the proper tokens.

LSP4IJ uses only extension point to implement feature like hover or go to déclaration compare to ballerina lsp which implement those features.

For lsp semantic tokens I would like to use too an extension point to be sure that in the future it will continue to work again.

Perhaps semantic highlighting is a bad idea, so if it that we could perhaps implement a syntaxic highlighter like textmate does and it is not linked to PsiElement

**Comment by FalsePattern** [comment]
I've successfully migrated to LSP4IJ in this branch: https://github.com/FalsePattern/ZigBrains/tree/lsp4ij

One main difference I've noticed between LSP4IJ and the ballerina LSP adapter, is that there is no simple way of attaching custom "hooks" to LanguageServer events, so I had to hook my semantic tokens refresh logic via the ConnectionProvider's handleMessage method.

See the updated HighlightingUtil class for the new implementation of the semantic tokens logic, maybe it could be easier to port to upstream.

**Comment by angelozerr** [comment]
> I've successfully migrated to LSP4IJ in this branch: https://github.com/FalsePattern/ZigBrains/tree/lsp4ij
> 

That is a great news for LSP4IJ !


What is your first feeling? Do you see some improvement or regression in term in feature?

> One main difference I've noticed between LSP4IJ and the ballerina LSP adapter, is that there is no simple way of attaching custom "hooks" to LanguageServer events, so I had to hook my semantic tokens refresh logic to `didOpen`/`didChange` via the ConnectionProvider's handleMessage method.
> 


Indeed today we have not this kind of mechanism . I think it is the same request than https://github.com/redhat-developer/lsp4ij/issues/380#issuecomment-2182630936

> See the updated HighlightingUtil class for the new implementation of the semantic tokens logic.

Thanks! I have started to implement RainbowVisitor and your code will help me a lot!

**Comment by FalsePattern** [comment]
I haven't noticed any major regressions, and autocomplete feels much more reliable compared to the old one.

The only blocker issues at this point is jumping to links in documentations causing an external editor to open, but I can see that there's already an open issue for it, so I will just wait until the next LSP4IJ update, then I will also push an update for ZB.

As for the semantic tokens, the best way to implement it in upstream, in my opinion, could be via a custom extension point, where a specific language server + language pair could have a "color provider" interface, such as:
```java
public interface SemanticTokenColorizer {
    /**
     * {@code null} means "use LSP4IJ fallback colorizer"
     * {@code Optional.empty()} means "no color"
     * And if not empty, use the color
     */
    @Nullable Optional<TextAttributesKey> getTokenColor(String tokenType, Set<String> tokenModifiers);
}
```
If no colorizer extension is specified for a server+language pair, use the previously mentioned fallback colorizer, which would map the predefined LSP semantic token types to `DefaultLanguageHighlighterColors`, for example:
```
"string" -> STRING
"keyword" -> KEYWORD
"function" -> FUNCTION_CALL
"function", ["declaration"] -> FUNCTION_DECLARATION
etc.
```

`com.falsepattern.zigbrains.zig.highlighter.ZigSyntaxHighlighter` and `com.falsepattern.zigbrains.zig.ide.ZigAttributes` contain a pretty extensive mapping for various token + modifier combinations used by ZLS+Zig, but most of them should also apply for any language.

**Comment by angelozerr** [comment]
> I haven't noticed any major regressions, and autocomplete feels much more reliable compared to the old one.
> 

Great! And now you can enjoy with LSP console https://github.com/redhat-developer/lsp4ij/blob/main/docs%2FUserGuide.md

> The only blocker issues at this point is jumping to links in documentations causing an external editor to open, but I can see that there's already an open issue for it, so I will just wait until the next LSP4IJ update, then I will also push an update for ZB.

Indeed I have created a PR with tests that we my team will review next week. The fix should be available soon in 0.0.3 but it will available only in nightly build not in release.

> 
> As for the semantic tokens, the best way to implement it in upstream, in my opinion, could be via a custom extension point, where a specific language server + language pair could have a "color provider" interface, such as:
> ```java
> public interface SemanticTokenColorizer {
>     /**
>      * {@code null} means "use LSP4IJ fallback colorizer"
>      * {@code Optional.empty()} means "no color"
>      * And if not empty, use the color
>      */
>     @Nullable Optional<TextAttributesKey> getTokenColor(String tokenType, Set<String> tokenModifiers);
> }
> ```
> If no colorizer extension is specified for a server+language pair, use the previously mentioned fallback colorizer, which would map the predefined LSP semantic token types to `DefaultLanguageHighlighterColors`, for example:
> ```
> "string" -> STRING
> "keyword" -> KEYWORD
> "function" -> FUNCTION_CALL
> "function", ["declaration"] -> FUNCTION_DECLARATION
> etc.
> ```
> 
> `com.falsepattern.zigbrains.zig.highlighter.ZigSyntaxHighlighter` and `com.falsepattern.zigbrains.zig.ide.ZigAttributes` contain a pretty extensive mapping for various token + modifier combinations used by ZLS+Zig, but most of them should also apply for any language.

My first goal is to have a semanticTokens support in a PR. If it works correctly we could discuss again to customize it with your suggestion.

The cancel support will work too since LSP4IJ support it.

**Comment by angelozerr** [comment]
> I've began testing the lsp4ij semantic tokens on a local dev branch, the only blocker now is just a typo that suppresses semanticTokensColorsProvider (https://github.com/redhat-developer/lsp4ij/pull/405), but aside from that, the semantic tokens seem to be working perfectly (with the default color scheme from lsp4ij).

It is a great news! And thanks for your PR, I have merged it.

**Comment by fbricon** [comment]
@FalsePattern Nightly LSP4IJ 0.3.0-20240704-134935 has been published with your fix

**Comment by FalsePattern** [comment]
Preview build published here:
https://github.com/FalsePattern/ZigBrains/releases/tag/16.0.0-pre1

**Comment by fbricon** [comment]
Tried it on PyCharm 2024.1.4. It didn't detect my zls on the path (installed from homebrew), I had to set the full path manually. 
It seems to work fine except for some reason, no hover requests are sent to the server. @angelozerr?

**Comment by fbricon** [comment]
@angelozerr looks like no hover for any LS on pycharm now, using latest nightly build  🙃

**Comment by angelozerr** [comment]
I did nothing about hover?

**Comment by fbricon** [comment]
my bad about hover. For some reason screen reader support got enabled, which disabled hover.
<img width="788" alt="Screenshot 2024-07-05 at 10 22 54" src="https://github.com/FalsePattern/ZigBrains/assets/148698/a65ce359-0f90-4efa-abd9-81bd6bea25a4">

**Comment by lppedd** [comment]
Injecting myself into this discussion to ask if integration with the built-in LSP support has been considered for Ultimate (and other paid IDEs) users. See [here](https://plugins.jetbrains.com/docs/intellij/language-server-protocol.html).

Not that it's important since the free alternatives work nicely, but just wondering if it would be feasible.

**Comment by FalsePattern** [comment]
The built in LSP has way less features than lsp4ij at this point, it's not even worth the effort.

**Comment by lppedd** [comment]
Makes sense! Thanks for the info.

**Comment by fbricon** [comment]
@FalsePattern I'm curious to know when do you plan on releasing your LSP4IJ-powered ZigBrains version?

**Comment by FalsePattern** [comment]
> @FalsePattern I'm curious to know when do you plan on releasing your LSP4IJ-powered ZigBrains version?

Once LSP4IJ 0.3.0 is released. The 16.0.0 preview of zigbrains depends on APIs added in that version, but it's still in just nightly releases, so i can't publish it on the marketplace.

https://github.com/redhat-developer/lsp4ij/milestone/3

**Comment by angelozerr** [comment]
@fbricon I think we can release LSP4IJ 0.3.0.

Badly I will not have time to do that, if you can do that it should be very cool.
