### ISSUE TITLE
zls doesn't work (clion win10)

### ISSUE THREAD

**Issue by sibkit** [FalsePattern/ZigBrains#57]
zls is in analyzing state, syntax highlighting and autocompletion do not work. win 10, CLion 2024.1.4, zls 0.13.0, zig-windows-x86_64-0.13.0

**Comment by Zelinzky** [comment]
Currently using your same setup, and I have no issue. Are both binaries, zls and the path to the toolchain set correctly in [File | Settings | Languages & Frameworks | Zig](jetbrains://CLion/settings?name=Languages+%26+Frameworks--Zig)?

**Comment by sibkit** [comment]
I reloaded zls from the site and the problem went away. It's strange that different versions of zls are published with the same name
