### ISSUE TITLE
`print` snippet does not auto-complete

### ISSUE THREAD

**Issue by AiziChen** [FalsePattern/ZigBrains#58]
When I type `prin` then press tab/enter key, snippet completion done well. but when I type total characters `print`, it does not doing complete automatically.

**Comment by AiziChen** [comment]
The same as snippet `main` does not work, too.

**Comment by FalsePattern** [comment]
Autocomplete is handled by the LSP4IJ plugin's `LSPCompletionContributor`, I have moved your bug report there: https://github.com/redhat-developer/lsp4ij/issues/435

**Comment by AiziChen** [comment]
has been fixed in: https://github.com/redhat-developer/lsp4ij/pull/440

**Comment by AiziChen** [comment]
has been fixed in: https://github.com/redhat-developer/lsp4ij/pull/440
