### ISSUE TITLE
Plugin doesn't recognize ranges in for loops

### ISSUE THREAD

**Issue by AnErrupTion** [FalsePattern/ZigBrains#6]
Consider this simple for loop with a range of numbers:

```
for (0..10) |_| {}
```

ZigBrains will throw an error over at the double dots:
```
'!', '(', ')', <addition op>, <bit shift op>, <bitwise op>, <compare op>, <multiply op>, <suffix op>, and, or or '{' expected, got '..'
```

But, of course, this compiles fine. Tested with ZigBrains 0.7.0.

**Comment by FalsePattern** [comment]
Should be fixed in 0.8.0. Seems like [zig-spec](https://github.com/ziglang/zig-spec) is a bit out of date.
