### ISSUE TITLE
Unable to "go to declaration" on stdlib items

### ISSUE THREAD

**Issue by zeroZshadow** [FalsePattern/ZigBrains#63]
When trying to "Go to declaration" on anything from the standard library, it will display the popup `Cannot find declaration to go to`.

For example, the following snippet wont have anything jump to the originating file:
```zig
const std = @import("std");

pub fn main() void {
    std.log.info("test\n", .{});
}
```
Neither any part in `std.log.info` or even the `"std"` in the import, will jump.

I'm using CLion 2024.2.1, and lastest master of ZLS (`ace6f6da90a4420cd6632363b30762e577e2b922`)
I've confirmed the issue isn't with ZLS, as this same action with the same project functions properly on vscode.
I'm also able to see the standard library under "External Libraries" in the Project view, and can open the files there to browse to the location it should be jumping too.

Please let me know if I can provide any additional info for the issue.

**Comment by MrLittleTexas** [comment]
Same issue on IntelliJ

**Comment by angelozerr** [comment]
Could you enable the LSP console trace https://github.com/redhat-developer/lsp4ij/blob/main/docs/UserGuide.md#lsp-console do you go to a declaration, and share the LSP trace in this issue please.

**Comment by angelozerr** [comment]
> Having done this see the following response from the `textDocument/definition` request
> 
> ```
> [Trace - 18:49:46] Received response 'textDocument/definition - (4)' in 1ms.
> Result: [
>   {
>     "originSelectionRange": {
>       "start": {
>         "line": 3,
>         "character": 12
>       },
>       "end": {
>         "line": 3,
>         "character": 16
>       }
>     },
>     "targetUri": "file:///c%3A/Users/myusername/scoop/apps/zig-dev/0.14.0-dev.1511+54b668f8a/lib/std/log.zig",
>     "targetRange": {
>       "start": {
>         "line": 189,
>         "character": 15
>       },
>       "end": {
>         "line": 189,
>         "character": 19
>       }
>     },
>     "targetSelectionRange": {
>       "start": {
>         "line": 189,
>         "character": 15
>       },
>       "end": {
>         "line": 189,
>         "character": 19
>       }
>     }
>   }
> ]
> ```
> 
> if I click on the returned file "url" I get an error about the file not being found.
> However if I open the file in Firefox OR replace the `%3A` with `:` it works.
> It might not like that escaped colon?

Indeed it is a good suspection. I need to find time to debug it.

**Comment by zeroZshadow** [comment]
Feel free to poke me on the Zig discord, I'd be happy to do any live debugging you'd like to do

**Comment by angelozerr** [comment]
@zeroZshadow could you share your project please.

**Comment by zeroZshadow** [comment]
This is reproducible using a fresh project from `zig init`.

**Comment by zeroZshadow** [comment]
I've done some more testing locally.
It seems the issue is due to the `0.14.0-dev.1511+54b668f8a` in the path. Specifically the `+` in the path is breaking things. If I replace this with a `-` or remove it, the issue is resolved.

**Comment by angelozerr** [comment]
Thanks for your great feedback.

**Comment by Pwera** [comment]
I think it doesn't work because of language server configuration.
When I'll setup:
![image](https://github.com/user-attachments/assets/005c7c43-6961-443d-a2ea-02d19c40fbcc)
LanguageServer configuration looks like this:
```json
{
  "zig_exe_path": "C:\\Users\\48788\\scoop\\apps\\zig\\0.13.0\\zig.exe",
  "zig_lib_path": "C:\\Users\\48788\\scoop\\apps\\zig\\0.13.0\\lib\\std",
  "enable_build_on_save": false,
  "build_on_save_step": "install",
  "dangerous_comptime_experiments_do_not_enable": false,
  "highlight_global_var_declarations": false
}
```
And completions/go to doens't work, but when I'll setup:
![image](https://github.com/user-attachments/assets/595b2aeb-7907-4750-be52-b7c33acb1a67)
Then configuration is refreshed:
```json
{
  "zig_exe_path": "C:\\Users\\48788\\scoop\\apps\\zig\\0.13.0\\zig.exe",
  "zig_lib_path": "C:\\Users\\48788\\scoop\\apps\\zig\\0.13.0\\lib",
  "enable_build_on_save": false,
  "build_on_save_step": "install",
  "dangerous_comptime_experiments_do_not_enable": false,
  "highlight_global_var_declarations": false
}
```
Remember to restart LangageServer connection.
![image](https://github.com/user-attachments/assets/c842e697-18f2-4a10-a568-2cc0f7603437)


LanguageServer configuration can be found here:
![image](https://github.com/user-attachments/assets/29e53ad6-376a-44db-a5cd-0696ed275217)

**Comment by MrLittleTexas** [comment]
@Pwera this fixed it for me, thanks!

**Comment by angelozerr** [comment]
Please note I did a fix to support the dot character (according to the comment https://github.com/FalsePattern/ZigBrains/issues/63#issuecomment-2344518417)

I'm waiting for feedback to merge my PR, if you wish to test please read https://github.com/redhat-developer/lsp4ij/issues/520#issuecomment-2345629479

**Comment by angelozerr** [comment]
@FalsePattern I think you can close this issue since it was a bug from LSP4IJ that I have fixed.

**Comment by KyussCaesar** [comment]
I had the same issue on a current version (19.3.0-241) of the plugin. I fixed it by disabling the "override" on the stdlib location (dunno why I ever had it enabled).
