### ISSUE TITLE
[LSP4IJ] No maximum length limit on inlay hints

### ISSUE THREAD

**Issue by platypusguy** [FalsePattern/ZigBrains#65]
Thanks for the very good plugin. I've run into a frustrating problem, though:

I tiyped in: `_ = class_file.readAll(buffer) catch |err` and on my 32" screen I cannot see the rest of the line due to the list of all possible errors extending all the way to column 576!

Below, I've attached a screen shot that shows the beginning of this very long line of suggestions.

As you can imagine, this makes reading and writing code difficult. Maybe you can list the options in a drop-down menu, rather than a long horizontal line. 

Until you fix this, how do I turn off this feature? 

![UnusableSuggestionsInZigBrains](https://github.com/user-attachments/assets/e1ae027c-6518-454c-af46-aa0c8c5208d5)

**Comment by FalsePattern** [comment]
I've forwarded the bug report to LSP4IJ

**Comment by FalsePattern** [comment]
Alright, i've made a workaround for this in the dev branch, inlay hints can now be toggled on/off in the plugin options, and `error{Foo, Bar, Baz}` blocks in inlay hints will get compacted to `error{...}` by default (also toggleable in the options).
It will be available in the next update.

**Comment by FalsePattern** [comment]
Available in 19.1.0
