### ISSUE TITLE
Debugger not available in GoLand

### ISSUE THREAD

**Issue by platypusguy** [FalsePattern/ZigBrains#66]
I'm running ZigBrains in Goland (paid version) on Windows 11. I have MSVC installed. I don't see any debugging options. They're all grayed out in ZigBrains. 

You wrote "Debugger settings are available in the Settings | Build, Execution, Deployment | Debugger menu, under the Zig section."

When I go to Settings | Build, Execution, Deployment | Debugger menu, there is no Zig section, nor in fact any mention of Zig. 

How do I get debugging support?

Thanks!

**Comment by FalsePattern** [comment]
Make sure you also installed the [Native Debugging Support](https://plugins.jetbrains.com/plugin/12775-native-debugging-support) plugin, zig should've given you a popup notification about it on startup.

**Comment by platypusguy** [comment]
Thank you for your prompt, clear response to this and the other issue I filed. I appreciate it and also very much appreciate the plugin.
