### ISSUE TITLE
label before switch statement breaks syntax and format

### ISSUE THREAD

**Issue by Khitiara** [FalsePattern/ZigBrains#67]
as of a recent zig dev version, [labeled continue syntax for switch statements](https://ziglang.org/documentation/master/#Labeled-switch) has been added. when using zigbrains, the editor treats the `:` after the label before the switch as a syntax error despite zls and the compiler handling it fine, and the editor format command removes all indentation before everything in the switch block recursively.

the specific syntax error: `'!', '(', ',', ':', ';', <addition op>, <assign op>, <bit shift op>, <bitwise op>, <compare op>, <multiply op>, <suffix op>, and, or or '{' expected, got ':'`

zig version: 0.14.0-dev.1860+2e2927735
zls version: 0.14.0-dev.168+6ae67e8
zigbrains version: 17.3.0-243
ide version: CL-243.19420.28

**Comment by FalsePattern** [comment]
Added support in 18.0.0, it's pending verification on the marketplace right now.

**Comment by FalsePattern** [comment]
Update: it's out on JB marketplace.
