### ISSUE TITLE
Support embedded languages in multi-line strings

### ISSUE THREAD

**Issue by DylanLukes** [FalsePattern/ZigBrains#70]
It's currently possible to just use `@embedFile` and have highlighting and language support work in a separate buffer, but it would be nice to be able to support IntelliJ's feature for injected language references for strings, especially multi-line strings.

https://www.jetbrains.com/help/idea/using-language-injections.html

This would be especially helpful for shaders, HTML, etc.

**Comment by FalsePattern** [comment]
Added in 18.1.0, works with both regular strings and multiline strings.
