### ISSUE TITLE
CLion / MacOS: Setup is not functioning the way it should

### ISSUE THREAD

**Issue by ashajjar** [FalsePattern/ZigBrains#71]
I installed Zig with brew, and followed the instructions.
however autocomplete only works when I give the full path of the executable.

<img width="726" alt="image" src="https://github.com/user-attachments/assets/b59331dd-b815-4a80-9196-dc2fca5b1593">

which works only for autocompleting but does not work for other stuff like when I try to run from the IDE

<img width="1115" alt="image" src="https://github.com/user-attachments/assets/2edfcb04-8f50-44af-8d73-391d12c6f4cd">

MacOS: 15.0.1 (24A348)

CLion 2024.2.2

Build #CL-242.22855.75, built on September 18, 2024

Runtime version: 21.0.3+13-b509.15 aarch64 (JCEF 122.1.9)
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o.

.NET Core v8.0.4 ARM64 (Server GC)

**Comment by ashajjar** [comment]
I solved the issue by pointing the plugin to the actual path not the link

<img width="729" alt="image" src="https://github.com/user-attachments/assets/8c2b6d29-7ef7-4c2d-bdf7-5b5b50404700">


/opt/homebrew/Cellar/zig/0.13.0/bin instead of /opt/homebrew/bin/zig

Because Homebrew creates a link:

<img width="843" alt="image" src="https://github.com/user-attachments/assets/b7bafa93-d776-42e7-a830-1631c4471ec3">

**Comment by FalsePattern** [comment]
For the symlink, you can just point it at `/opt/homebrew/bin`, ZigBrains will look for `zig` inside the directory. The standard library path itself is pulled from `zig env`

**Comment by ashajjar** [comment]
> For the symlink, you can just point it at `/opt/homebrew/bin`, ZigBrains will look for `zig` inside the directory. The standard library path itself is pulled from `zig env`

when I pointed it to `/opt/homebrew/bin` that did not work either. The screen shot is from the second attempt 😅
