### ISSUE TITLE
CLion breaks entirely with plugin enabled

### ISSUE THREAD

**Issue by jacobef** [FalsePattern/ZigBrains#76]
Every CLion project, including non-Zig projects, fails to open and freezes the IDE with the latest plugin update, forcing me to force quit then disable the plugin.

**Comment by FalsePattern** [comment]
Fixed in 20.0.1

**Comment by FalsePattern** [comment]
@jacobef @InfinitlyUndefined can you please install the plugin via the zip from the github release and check if the fix works on your systems? Marketplace verification is taking a long time
