### ISSUE TITLE
Can't run tests on v20

### ISSUE THREAD

**Issue by bfreis** [FalsePattern/ZigBrains#77]
Since the v20 upgrade, a lot of things broke. Some were fixed by completely reconfiguring the plugin, but an annoying one remains: I can't run tests.

If I try to run tests, I get an error popup message about an "Unexpected JSON token ...", it then references some environment variables (e.g. "GONOSUMDB": null, "GOPROXY": null). I noticed a "Use direnv" checkbox on the run configuration for the test, which I don't recall. It was checked.

If I uncheck "use direnv" on the run configuration, it makes a bit more progress, but still doesn't work: instead of that error popup, it tries to run the application instead of trying to run the tests. This is a lib-only project, so the Run window just shows some Zig output saying that there's no member named main, as expected.

**Comment by FalsePattern** [comment]
The test bug is fixed in 20.0.1, please check if the direnv thing still happens too.

**Comment by bfreis** [comment]
That's awesome!

I don't see the update available yet in the Plugins settings — do I need to do anything special to get it?

Thanks!

**Comment by bfreis** [comment]
I was able to download and install the 20.0.1 zip, and the issues I was encountering are gone. Thanks!
