### ISSUE TITLE
Can't jump to the definition when the member variable of the struct is named @"xxx".

### ISSUE THREAD

**Issue by MINGtoMING** [FalsePattern/ZigBrains#83]
![Screencast from 2024-11-12 22-41-22 (1)](https://github.com/user-attachments/assets/365bda06-8ee5-41f3-83a4-45b05fda0485)

**Comment by FalsePattern** [comment]
Jump to definition is handled by [ZLS](https://github.com/zigtools/zls) through [LSP4IJ](https://github.com/redhat-developer/lsp4ij), please report this to them.
