### ISSUE TITLE
Syntax bug

### ISSUE THREAD

**Issue by MitchPattern123** [FalsePattern/ZigBrains#88]
Consider the following function:
```zig
fn printFields(comptime T: type) void {
    std.log.info("Fields of struct '{s}':", .{@typeName(T)});
    inline for (std.meta.fields(T),) |field| {
        std.log.info("{s}", .{field.name});
    }
}
```
![image](https://github.com/user-attachments/assets/9f6dfb71-6032-44b7-8d84-05150444b7a6)
I get `<for operand> expected, got '('`.
It compiles and works with both, the comma present and not.

**Comment by FalsePattern** [comment]
Fixed in 20.1.1
