### ISSUE TITLE
Several bugs in LSP integration

### ISSUE THREAD

**Issue by zlw** [FalsePattern/ZigBrains#9]
👋 first of all, thanks for the work on this plugin, not having Zig support was the only reason I had to switch to VSCode

However, there're some things that are not working 😓 
Sadly, I don't have any Java and LSP experience to look at it, so best I can do is leave this here 😄 
Let me know if you have any questions or I can provide you with some debug logs or anything 🙌 

## Versions
* Zigbrains: 0.8.0
* RubyMine: 2023.2.1
* Zig: 0.11.0
* ZLS: 0.11.0

## Zig configuration:
<img width="714" alt="Screenshot 2023-08-28 at 15 32 56" src="https://github.com/FalsePattern/ZigBrains/assets/39616/802313a6-b014-4fd5-8456-b14ba84b5804">

## ZLS configuration:
<img width="709" alt="Screenshot 2023-08-28 at 15 33 06" src="https://github.com/FalsePattern/ZigBrains/assets/39616/ea811f2f-b481-42ce-852a-634138c970b4">

## Problems:

Note: I'm using exact same Zig/ZLS versions in VSCode where I don't observe this issues, so it looks like something doesn't work in the integration with ZLS, not ZLS itself

### Status icon
Icon stays red after opening Zig project, after clicking "Restart server" it turns green. It is never yellow so I'm not sure if this is some false positive or something. However, connected files look ok - all the open files are listed there.

### Autocompletion
Autocompletion works only sometimes. It works for some struct fields, but not for others. It does not suggest functions from structs assigned to fields (eg. Allocator).

### Go to Definition
Does not work at all. Within project or for std.

### Syntax highlighting, argument hints etc.
They work upon opening a file, but right after making any change (eg. adding a newline anywhere in the source code) the highlighting is all around broken, argument hints move to random places in the source code like in screenshot below.

I tried it with multiple themes, so it's not a theme issue.

<img width="497" alt="Screenshot 2023-08-28 at 18 11 46" src="https://github.com/FalsePattern/ZigBrains/assets/39616/c2c62342-9be4-4141-8605-c6d9ad2c1386">

**Comment by TheStachelfisch** [comment]
> Go to Definition
> Does not work at all. Within project or for std.

Go to definition works for me, but it doesn't have any visual feedback when hovering.

> Syntax highlighting, argument hints etc.
They work upon opening a file, but right after making any change (eg. adding a newline anywhere in the source code) the highlighting is all around broken, argument hints move to random places in the source code like in screenshot below.
> 
> I tried it with multiple themes, so it's not a theme issue.

I have only observed argument hints moving to random places

**Comment by lumynou5** [comment]
same problem

**Comment by zlw** [comment]
> Go to definition works for me, but it doesn't have any visual feedback when hovering.

For me it's not only the feedback. Please check screenshot below. `fromU8` clearly exists, but RubyMine says it can't find declaration. This works in VSCode, Helix and Neovim etc. so LSP itself seems okay

<img width="1512" alt="Screenshot 2023-08-30 at 10 15 53" src="https://github.com/FalsePattern/ZigBrains/assets/39616/79c23664-71ea-4590-be0c-b9775964f45f">

**Comment by obask** [comment]
Clicking on an error definition for an unused variable makes a whole file being highlighted red(CLion24.1), both 0.11 and 0.12 zls versions have this issue.
![Screenshot 2024-04-13 at 6 28 11 PM](https://github.com/FalsePattern/ZigBrains/assets/13053173/6e66360e-b4fe-448e-8511-cb70b1a49395)
PS an initial highlight pass finishes correctly and only highlights an unused variable

**Comment by FalsePattern** [comment]
I've reworked some of the LSP logic in 14.0.0, all these issues should be fixed now.

Syntax highlighting can still occasionally break when running a file reformatting, but closing and opening the editor fixes it.

**Comment by FalsePattern** [comment]
No longer relevant since 16.0.0-pre1, LSP integration is handled by LSP4IJ.
